# Generated by Django 5.2.13 on 2026-08-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janSetu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civicissue',
            name='status',
            field=models.CharField(choices=[('Reported', 'Reported'), ('AI Verified', 'AI Verified'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Pending Citizen Verification', 'Pending Citizen Verification'), ('Verified Resolved', 'Verified Resolved')], default='Reported', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
