# Generated by Django 6.1 on 2026-08-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janSetu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otprecord',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='otprecord',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=254),
            preserve_default=False,
        ),
    ]
