# Generated by Django 5.2.13 on 2026-08-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janSetu', '0002_alter_civicissue_status_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.TextField(blank=True, default='https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=400&auto=format&fit=crop&q=80', null=True),
        ),
    ]
