# Generated by Django 5.2.13 on 2026-08-17 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janSetu', '0002_remove_otprecord_phone_number_otprecord_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='aadhaar_linked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.URLField(blank=True, default='https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=400&auto=format&fit=crop&q=80', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='badges',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='customuser',
            name='karma_xp',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='level_title',
            field=models.CharField(default='Active Citizen', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('officer', 'Officer'), ('corporator', 'Corporator')], default='citizen', max_length=15),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stats',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verified_citizen',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ward',
            field=models.CharField(blank=True, default='Shanti Nagar', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ward_number',
            field=models.IntegerField(blank=True, default=42, null=True),
        ),
        migrations.CreateModel(
            name='CivicIssue',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Roads', 'Roads'), ('Water', 'Water'), ('Sanitation', 'Sanitation'), ('Electricity', 'Electricity'), ('Waste', 'Waste'), ('Traffic', 'Traffic'), ('Parks', 'Parks')], max_length=20)),
                ('status', models.CharField(choices=[('Reported', 'Reported'), ('AI Verified', 'AI Verified'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Reported', max_length=20)),
                ('urgency', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Moderate', 'Moderate'), ('Low', 'Low')], max_length=20)),
                ('location', models.JSONField()),
                ('images', models.JSONField()),
                ('ai_analysis', models.JSONField(blank=True, null=True)),
                ('assigned_department', models.CharField(blank=True, max_length=150, null=True)),
                ('timeline', models.JSONField(blank=True, default=list)),
                ('upvotes', models.IntegerField(default=1)),
                ('comments_count', models.IntegerField(default=0)),
                ('verification_votes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_issues', to=settings.AUTH_USER_MODEL)),
                ('upvoted_users', models.ManyToManyField(blank=True, related_name='upvoted_issues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='janSetu.civicissue')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('issue_id', models.CharField(blank=True, max_length=50, null=True)),
                ('action_url', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
