# Generated by Django 5.2.13 on 2026-08-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("janSetu", "0003_alter_customuser_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
