# Generated by Django 5.2.13 on 2026-08-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janSetu', '0004_profile_number'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='otprecord',
            index=models.Index(fields=['target', 'is_verified', 'expires_at'], name='janSetu_otp_target_7923b9_idx'),
        ),
    ]
