# Generated by Django 5.2.13 on 2026-09-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janSetu', '0005_otprecord_jansetu_otp_target_7923b9_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='civicissue',
            name='merged_ticket_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='civicissue',
            name='times_reported',
            field=models.IntegerField(default=1),
        ),
    ]
