# Generated by Django 5.2.13 on 2026-09-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janSetu', '0006_civicissue_merged_ticket_ids_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('department', models.CharField(default='Municipal Corporation', max_length=100)),
                ('pincodes', models.JSONField(blank=True, default=list)),
                ('urgency', models.CharField(default='Advisory', max_length=20)),
                ('category', models.CharField(default='General Advisory', max_length=100)),
                ('author_name', models.CharField(blank=True, max_length=150, null=True)),
                ('author_role', models.CharField(default='officer', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
