# Generated by Django 5.2.13 on 2026-09-02 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("janSetu", "0007_announcement"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(default="Infrastructure", max_length=100),
                ),
                ("ward_name", models.CharField(default="Ward 42", max_length=100)),
                ("pincode", models.CharField(default="751030", max_length=10)),
                (
                    "allocated_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "spent_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Proposed", "Proposed"),
                            ("Under Voting", "Under Voting"),
                            ("Approved", "Approved"),
                            ("Funded", "Funded"),
                            ("In Construction", "In Construction"),
                            ("Completed", "Completed"),
                        ],
                        default="Proposed",
                        max_length=50,
                    ),
                ),
                ("community_votes", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "proposed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposed_budgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
