# Generated by Django 5.2.13 on 2026-09-02 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janSetu', '0008_budgetallocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsensusPoll',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=150)),
                ('ward', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('yes_votes', models.IntegerField(default=0)),
                ('no_votes', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Active Ballot', 'Active Ballot'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Active Ballot', max_length=50)),
                ('days_left', models.IntegerField(default=14)),
                ('budget_estimate', models.CharField(default='₹ 45.0 Lakhs', max_length=100)),
                ('created_by_name', models.CharField(blank=True, max_length=150, null=True)),
                ('voted_users', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_polls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WardBudgetProposal',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('required_budget', models.DecimalField(decimal_places=2, default=2500000.0, max_digits=14)),
                ('current_votes', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Open for Voting', 'Open for Voting'), ('Threshold Met', 'Threshold Met'), ('In Execution', 'In Execution')], default='Open for Voting', max_length=50)),
                ('ward_pin', models.CharField(default='751024', max_length=50)),
                ('created_by_name', models.CharField(blank=True, max_length=150, null=True)),
                ('voted_users', models.JSONField(blank=True, default=list)),
                ('linked_poll_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
