# Generated by Django 5.2.13 on 2026-09-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janSetu', '0009_consensuspoll_wardbudgetproposal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='civicissue',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['is_active', 'department'], name='janSetu_ann_is_acti_5ec545_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['created_at'], name='janSetu_ann_created_e5342f_idx'),
        ),
        migrations.AddIndex(
            model_name='civicissue',
            index=models.Index(fields=['pin_code', 'status', 'is_hidden_from_map'], name='janSetu_civ_pin_cod_8342f3_idx'),
        ),
        migrations.AddIndex(
            model_name='civicissue',
            index=models.Index(fields=['category', 'status'], name='janSetu_civ_categor_d2d012_idx'),
        ),
        migrations.AddIndex(
            model_name='civicissue',
            index=models.Index(fields=['created_at'], name='janSetu_civ_created_d1905e_idx'),
        ),
        migrations.AddIndex(
            model_name='consensuspoll',
            index=models.Index(fields=['ward', 'status'], name='janSetu_con_ward_03f117_idx'),
        ),
        migrations.AddIndex(
            model_name='consensuspoll',
            index=models.Index(fields=['department', 'status'], name='janSetu_con_departm_dcbdf1_idx'),
        ),
        migrations.AddIndex(
            model_name='consensuspoll',
            index=models.Index(fields=['created_at'], name='janSetu_con_created_07dddf_idx'),
        ),
        migrations.AddIndex(
            model_name='wardbudgetproposal',
            index=models.Index(fields=['ward_pin', 'status'], name='janSetu_war_ward_pi_002b22_idx'),
        ),
        migrations.AddIndex(
            model_name='wardbudgetproposal',
            index=models.Index(fields=['category', 'status'], name='janSetu_war_categor_1f33a3_idx'),
        ),
        migrations.AddIndex(
            model_name='wardbudgetproposal',
            index=models.Index(fields=['created_at'], name='janSetu_war_created_aea1ff_idx'),
        ),
    ]
